userbotindo/Anjani

- anjani_bot/utils/tools.py
- added rand_key and rand_array
> Some handy utils

- anjani_bot/core/language/en.yml
- anjani_bot/plugins/admin.py
Signed-off-by: TomyPrs <tomy.prs25@gmail.com>
> admin: add zombies cmd

- language/en.yml
- language/id.yml
Update little translation. Im sorry hehehe.
> Little translation

- language/id.yml
-update in line 318 change simply to secara sederhana
-delete line 346, which contain  \nhandle bisa menjadi Id pengguna atau username pengguna
-change administrator to Administrator in several line
-change name to nama and fedid to ID Federasi
-change user_id to ID Pengguna in information so users will not confuse
-change reply to balas pesan
> Fix Translation

- anjani/filters.py
Admin command from Anonymous Admin and Linked Channel Owner are still executed
Signed-off-by: wulan17 <galihgustip@gmail.com>
> Anjani: Ignore admin command from Anonymous channel

- anjani/util/db/client.py
- anjani/util/db/client_session.py
- anjani/util/db/collection.py
- anjani/util/db/command_cursor.py
- anjani/util/db/cursor_base.py
- anjani/util/db/db.py
- anjani/util/db/types.py
#68
Change-Id: I86057e6889ba65d7a1b3754804883deeffa4ed0a
> Anjani: Database: follow mongodb 4.0 update

- anjani/plugins/welcome.py
`Since telegram set first name as *required will never return None even using blank font`
> welcome: replace username with mention instead.

- anjani/plugins/admins.py
- anjani/plugins/backups.py
- anjani/plugins/language.py
- anjani/plugins/main.py
- anjani/plugins/purge.py
- language/en.yml
- language/id.yml
for chat using ctx.chat instead ctx.msg.chat
Signed-off-by: tomyprs <tomy.prs25@gmail.com>
translation: update for gpic success
Signed-off-by: tomyprs <tomy.prs25@gmail.com>
> Minor Changes

- anjani/filters.py
- anjani/language/en.yml
- anjani/language/id.yml
- anjani/plugins/lockings.py
- anjani/plugins/spam_prediction.py
This plugin will help admin/owner on the group to lock spesific types or permissions.
> Plugins: add Lockings

- anjani/language/en.yml
- anjani/language/id.yml
Signed-off-by: tomyprs <tomy.prs25@gmail.com>
> languages: spell checkup

- anjani/core/event_dispatcher.py
- anjani/error.py
- anjani/plugins/backups.py
- anjani/util/misc.py
> Stop propagation

- anjani/core/telegram_bot.py
- anjani/plugins/federation.py
- anjani/plugins/filters.py
- anjani/plugins/lockings.py
- anjani/plugins/main.py
- anjani/plugins/notes.py
- anjani/plugins/restriction.py
- anjani/plugins/spam_shield.py
- anjani/plugins/staff_tools.py
- anjani/plugins/stats.py
- anjani/plugins/welcome.py
This PR optimize several database queries making sure data filtering process is done on the database reducing bot loads. The returned data is also projected according to the required data only.
addition:
- Remove misleading fban data  on `/stats` "x% from total users" as the banned data are not guaranteed to be unique user every feds. Also added fbanned chats count
> Optimize database query

- anjani/plugins/spam_prediction.py
Model are refreshed at 17:00 UTC (00:00 WIB). That time the model daily training jobs should been done.
> SpamPrediction: Add model refresh scheduler

- anjani/language/en.yml
- anjani/language/id.yml
- anjani/plugins/misc.py
* This change default service from spacebin to stashbin
* Remove katbin from paste service
* Update hastebin urls
* Add error log on `/paste` failed
> Misc: Add stashbin service for /paste

- anjani/plugins/canonical.py
-> Currently on testing for some groups
Change-Id: I27664828363f14a2e37414018ffed994462e34b5
> feat(Canonical): save admin chat into database

- anjani/language/en.yml
- anjani/language/id.yml
- anjani/plugins/restriction.py
This commits also refactor `/ban` command.
Change-Id: I201c8fc1cd013b06cb9c08a37f0f3f069931c7d6
> feat(restriction): add sban command

- anjani/util/tg.py
Minor Change code used ``if reply_msg: to avoid using too many if and elif statements.``
> refactor(tg): minor code improvement

- anjani/core/anjani_bot.py
- anjani/core/telegram_bot.py
- anjani/main.py
-> This also partially reverts commit 6e93814114a601de0bd7cce52da0ef78395771d0.
-> Hack for aiorun without uvloop bug
Change-Id: Iaa0cc3234283c8fc34cc2c1340e787d1843461a6
> refactor(idle): improve idle

- .github/workflows/release.yml
- .github/workflows/run-test.yml
- anjani/core/telegram_bot.py
- anjani/main.py
- run bot until complete
- add PyPI publish jobs
> chore(workflow): run bot until complete

- anjani/language/en.yml
- anjani/language/id.yml
- anjani/plugins/main.py
Change-Id: I6536c1e8469f723c8a18b78bd1e96b1d65349fa9
> fix(rules): failed to fetch if bot is banned

- Dockerfile
- anjani/core/telegram_bot.py
Make sure poetry deps are cached on the layer. 
Only rebuild dependency layer when `pyproject.toml` or `poetry.lock` are updated
> build(Dockerfile): Faster build time

- anjani/language/en.yml
- anjani/language/id.yml
- anjani/plugins/welcome.py
-> Change parsing error message to make it universal 
Change-Id: I0e5f341401c876a39150630da9bfbafd6aea8bd9
> fix(welcome): fix value error on unmatched brancket

- anjani/util/tg.py
> fix(util): button parser TypeError when parsing non text message

- anjani/core/telegram_bot.py
blame(a1059b6eb7710c285091bcfb69f2a80852265a30)
Change-Id: I7f5e0461c28857caf627ba08a62b93b67d1e6318
> fix(anjani): signal handler on windows

- anjani/plugins/canonical.py
Save chat profile picture to database on `/r` command. This images will be used on dashboard.
> feat(canonical): save chat photo to database

- anjani/plugins/federation.py
> refactor(federation): add bulk ban method

- anjani/language/en.yml
- anjani/language/id.yml
- anjani/plugins/welcome.py
- Add support to add custom media welcome messages
> feat(welcome): Add media welcomes

- anjani/plugins/filters.py
> fix(filters): backup failing unhasable dict

- anjani/language/id.yml
> change some text ID lang.

- Dockerfile
> build(Dockerfile): bump to python 3.10

- anjani/plugins/canonical.py
- docker-compose.yml
- entrypoint.sh
- Bump [userbotindo-kit@v0.1.1](https://github.com/userbotindo/userbotindo_kit/releases/tag/v0.1.1)
This feature only runs on @dAnjani_bot with the internal package userbotindo-kit
> feat(canonical): add health-check web service

- Dockerfile
- docker-compose.yml
- entrypoint.sh
this avoid installing package on every container restart. 
installed package are also pruned
> build(Dockerfile): download internal package on layer

- anjani/language/en.yml
- anjani/language/id.yml
> chore: update missleading help string

- anjani/language/en.yml
- anjani/language/id.yml
- anjani/plugins/main.py
> chore: add status page button on start command

- anjani/core/command_dispatcher.py
- anjani/core/event_dispatcher.py
- anjani/main.py
- config.env_sample
unhandled command/event dispatcher will propagate alert
Added ENV `ALERT_LOG`
> feat: add alert dispatcher

- Dockerfile
- anjani/plugins/canonical.py
- anjani/util/types.py
- entrypoint.sh
- preinstall.sh
> chore: bump userbotindo_kit to v0.1.2

- anjani/language/en.yml
- anjani/plugins/federation.py
> fix(federation): unhandled fed stats invalid input

- anjani/language/en.yml
- anjani/language/id.yml
- anjani/plugins/lockings.py
Close #320 
Change-Id: I2a5d7690c4f486642c48a0f32365b86257e1d409
> fix(lockings): tell if bot don't have full permission to lock

- anjani/language/id.yml
> chore(lang/id): fix paste wording

- anjani/plugins/debug.py
> fix(debug): redirect eval stdout output

- anjani/core/anjani_bot.py
- anjani/core/database_provider.py
- anjani/core/event_dispatcher.py
- anjani/core/telegram_bot.py
- anjani/main.py
- anjani/plugins/canonical.py
- anjani/plugins/federation.py
- anjani/plugins/main.py
- anjani/plugins/spam_shield.py
- anjani/util/config.py
Current Config implementation allows dynamic attribute setter and getter. This might introduce a risk of bugs when accessing undefined environments attributes in the future.
This change config object to strictly typed ensuring that attribute assignments and retrievals follows the pre-defined attribute. This enhancement minimizes the chances of encountering runtime errors and facilitates better code maintenance and debugging.
> reafactor(config): strict type config

- anjani/plugins/spam_shield.py
- poetry.lock
- pyproject.toml
> fix(SpamShield): locale string not found

- anjani/core/plugin_extenter.py
- anjani/util/config.py
Change-Id: I0e23778909d637144975d239a91375288b904220
> fix(config): properly add the disabled plugin to runtime

- anjani/plugins/notes.py
- anjani/util/tg.py
-> After #1ac9aaca3210186f47495660efe276cab1b50236
Change-Id: I04c7f6f2b693e20ca9c4e9eab2363ab76aa682b5
> fix(notes): breaking button for media

- anjani/plugins/canonical.py
- anjani/util/types.py
- docker-compose.yml
- preinstall.sh
- In this version health check endpoint was moved to `/health` from `/`
- Added web server done callback
> chore: bump userbotindo-kit to v0.1.3

- anjani/core/telegram_bot.py
- anjani/plugins/main.py
- anjani/util/config.py
> feat: add feature flag

- anjani/plugins/welcome.py
> fix(welcome): handle bulk new chat member

- anjani/plugins/main.py
> fix(main): keep updating session state

- anjani/core/command_dispatcher.py
- anjani/core/telegram_bot.py
Related to -> [#261](https://github.com/userbotindo/Anjani/pull/261)
Change-Id: Id8abb222daac88a0d1535258eb85555573d83f06
> feat(core): add rate limiter to callbackquery

- anjani/plugins/users.py
> fix(user): handle case when first_name is None

- Dockerfile
This PR enhance docker build steps to use multi stage build reducing the image size from ±700MB to ±450MB (with internal library) and ±400MB to ±200MB (without internal library)
> build: enhance docker image size

- .github/workflows/build-image-staging.yml
> chore(build-image): add check to run jobs

- Dockerfile
> chore: add doppler to base image

- anjani/language/en.yml
- anjani/language/id.yml
- anjani/plugins/topic.py
Adds several topic commands:
- /actiontopic
- /createtopic <topic name>
- /renametopic <topic name>
- /opentopic
- /closetopic
- /deletetopic
> feat: add more topic command

- anjani/plugins/misc.py
> fix(misc): change stasahbin scheme to https

- anjani/internal_plugins/spam_prediction.py
- anjani/plugins/federation.py
- anjani/plugins/spam_shield.py
- anjani/plugins/users.py
- anjani/plugins/welcome.py
- anjani/util/tg.py
Hanlde telegram collectibles  (*multiple) username
Resolve #378
> fix: handle collectibles username 

- anjani/language/en.yml
- anjani/language/id.yml
- anjani/plugins/lockings.py
'other_message' will have the type respectively https://github.com/Mayuri-Chan/pyrofork/commit/7af2b07be33e64ce3a3487121789448a3d33a45e
- audio
- docs
- games
- gifs
- inline
- prhotos
- plain
- videonote
- stickers
- videos
- voices
> fix(locking): invalid `can_send_other_messages` args
